name: go-oidc-mock

services:
  api:
    build:
      context: .
    image: go-oidc-mock:dev
    environment:
      GO_OIDC_MOCK_ISSUER_URL: http://localhost:8080
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped
