version = 1

[provenance]
signer_workflow = "meigma/go-oidc-mock/.github/workflows/release.yml"

[[packages]]
name = "go-oidc-mock"
description = "Mock OIDC/OAuth server for tests."
tag_pattern = "v${version}"

[[packages.assets]]
os = "darwin"
arch = "amd64"
pattern = "go-oidc-mock_${version}_darwin_amd64"

[[packages.assets]]
os = "darwin"
arch = "arm64"
pattern = "go-oidc-mock_${version}_darwin_arm64"

[[packages.assets]]
os = "linux"
arch = "amd64"
pattern = "go-oidc-mock_${version}_linux_amd64"

[[packages.assets]]
os = "linux"
arch = "arm64"
pattern = "go-oidc-mock_${version}_linux_arm64"

[[packages.binaries]]
path = "go-oidc-mock"
